client_id = "77e6d604777aba4f14e39d1145123fbe"
name = "Calendify Delivery"
application_url = "https://calendario-envios.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [ 
  "https://calendario-envios.vercel.app/auth/callback"
]

[app_proxy]
url = "https://calendario-envios.vercel.app"
subpath = "proxy"
prefix = "apps"

[extensions]
embedded = true

  [[extensions.development]]
  root = "extensions/cart-calendar"